In [24]:
import pandas as pd
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import cross_val_score

In [20]:
df = pd.read_csv("crit_regression.txt", sep="\t")
display(df)
df.shape # (13,4)
df.columns # Index(['Crit Chance', 'Legendary', 'Fabled', 'Mythical'], dtype='object')

Crit Chance  Legendary  Fabled  Mythical
0           946        6.2     1.9       0.1
1          1094        6.0     1.5       0.1
2          1094        6.3     2.1       0.2
3          1111        6.5     1.9       0.2
4          1111        6.2     2.8       0.3
5          1222        6.3     2.5       0.2
6          1270        6.5     2.7       0.3
7          1270        6.7     2.6       0.4
8          1386        6.5     2.9       0.4
9          1568        7.0     2.9       0.4
10         1568        6.7     2.9       0.4
11         1568        6.9     2.9       0.4
12         1586        7.0     3.0       0.5

Index(['Crit Chance', 'Legendary', 'Fabled', 'Mythical'], dtype='object')

In [28]:
# normalize(df[['Legendary','Fabled', 'Mythical']], axis=0)
X = df["Crit Chance"].values.reshape(-1, 1)
Y = df[["Legendary","Fabled","Mythical"]]

reg = LinearRegression().fit(X, Y)
reg.score(X, Y)

0.7282315037081036

In [30]:
# Define the models to test
models = [
    LinearRegression(),
    Ridge(),
    Lasso(),
    ElasticNet(),
    # SVR(),
    RandomForestRegressor(),
    # GradientBoostingRegressor(),
    MLPRegressor()
]

# Evaluate the models using cross-validation
for model in models:
    scores = cross_val_score(model, X, Y, cv=5, scoring="r2")
    print(f"{model.__class__.__name__}: R^2 = {scores.mean():.3f} (+/- {scores.std():.3f})")

LinearRegression: R^2 = -1.720 (+/- 1.168)
Ridge: R^2 = -1.720 (+/- 1.168)
Lasso: R^2 = -1.791 (+/- 1.255)
ElasticNet: R^2 = -1.753 (+/- 1.208)
RandomForestRegressor: R^2 = -3.136 (+/- 1.774)
MLPRegressor: R^2 = -112941.786 (+/- 104224.407)


In [31]:
# Print the coefficients
print("Coefficients:", reg.coef_)

Coefficients: [[0.00127579]
 [0.00176688]
 [0.00050985]]


In [33]:
x_new = 5000
y_pred = reg.predict([[x_new]])
display(y_pred)

array([[11.25391801,  9.05956322,  2.19059608]])

In [35]:
weights = np.array([1.25, 1.65, 2])
result = np.dot(y_pred / 100, weights)
display(weights)

array([1.25, 1.65, 2.  ])

In [36]:
display(result
    )

array([0.33396869])

In [ ]:




x_new = 5000
y_pred = reg.predict([[x_new]])
weights = np.array([1.25, 1.65, 2])
result = np.dot(y_pred / 100, weights)